package:
  name: dtw
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.1') }}

source:
  path: ../..
#  git_url: https://gitlab.inria.fr/cgodin-dev/dtw
  git_tag: master

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', '0') }}

requirements:
  build:
    - python {{ python }}
    - setuptools
  host:
    - python {{ python }}
  run:
    - python {{ python }}
    - numpy
    - matplotlib

about:
  summary: Dynamic time warping algorithm(s)
  dev_url: https://gitlab.inria.fr/cgodin-dev/dtw
